### ISSUE TITLE
Can't Change The Node Color

### ISSUE THREAD

**Issue by ruhkhism26** [socnetv/app#107] opened 2020-07-12 15:59 UTC
i cannot change the node color, when i tried to change it from properties, it changed. But then back into default color when click somewhere, please give me solution..

**Comment by oxy86** [comment] 2020-07-13 12:46
Hello, thanks for reporting this issue. It seems your issue is a duplicate of #93. 
That bug has been fixed in dev branch (2.6-dev).
You may download 2.6-dev executables from here:
https://github.com/socnetv/app/releases/tag/continuous

Please test and report back if you experience the problem :)

**Closed** 2020-12-28 12:06 UTC
Labels: duplicate
